# Generated by Django 5.1.6 on 2025-02-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beauty_salon", "0006_alter_review_appointment_alter_review_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="image",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
    ]
