# Generated by Django 5.1.6 on 2025-02-23 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beauty_salon", "0012_remove_appointment_service_appointment_services"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="services",
        ),
        migrations.AddField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="beauty_salon.service",
            ),
            preserve_default=False,
        ),
    ]
