# Generated by Django 5.2 on 2025-04-21 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beauty_salon", "0014_historicalappointment"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together={("client", "date", "time")},
        ),
    ]
