services:
  web:
    build: .
#    container_name: beauty_salon_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - mailhog

  redis:
    image: redis:latest
#    container_name: beauty_salon_redis
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog:latest
    container_name: beauty_salon_mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI

  celery:
    build: .
#    container_name: beauty_salon_celery
    command: celery -A conf worker --loglevel=info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - web
      - redis

  celery-beat:
    build: .
#    container_name: beauty_salon_beat
    command: celery -A conf beat --loglevel=info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - web
      - redis
